# Path to your oh-my-zsh configuration.
ZSH=/home/mbidon/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often to auto-update? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to the command execution time stamp shown 
# in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=$PATH:"/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export PATH="$PATH:/home/mbidon/.rvm/bin/"
export PATH="$PATH:/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/eclipse"
export PATH="$PATH:/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/android-ndk-r10/"
export PATH="$PATH:/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/sdk/platform-tools/"
export PATH="$PATH:/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/sdk/tools"
export PATH="$PATH:/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/sdk/build-tools/android-4.4/"
export PATH="$PATH:/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/sdk/build-tools/19.1.0"
export PATH="$PATH:/home/mbidon/Downloads/p4v-2014.2.951414/bin"
export PATH="$PATH:/home/mbidon/Tools/"
export PATH="$PATH:/home/mbidon/Tools/android-studio/bin"
#export NETATMO_APPS_ANDROID='/home/mbidon/Prog/netatmo/apps/Android/eclipse/workspace'
export ANDROID_HOME_NDK='/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/android-ndk-r10/'
export ANDROID_HOME='/home/mbidon/Tools/adt-bundle-linux-x86_64-20140624/sdk'
export WS='/home/mbidon/Prog/git/android/workspace/WeatherStationClient'
export TS='/home/mbidon/Prog/git/android/workspace/NetatmoThermostat'
export CM='/home/mbidon/Prog/git/android/workspace/Camera'

export PAGER=most
export EDITOR=vim

export NETATMO_ANDROID_PASSFILE='/home/mbidon/pwd2.txt'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export MGT_KEY="ae0060f9454bb6e705b4b834225bba9d"
export PATH="$PATH:/home/mbidon/Prog/netatmo/apps/Linux/flasher"

# aliases
source /usr/local/bin/virtualenvwrapper.sh

# Custom autosuggest
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=2'

# Tmux configuration
# Not necessary with urxvt
# # alias tmux='TERM=xterm-256color tmux -2'

# Shameless
alias gut="git"
